#!/usr/bin/env python3
"""Bouwt de statische toolkaarten in index.html uit data.json, zodat de
directory indexeerbaar is zonder JavaScript. Draait in de GitHub Action
(sync-data.yml) na elke update van de centrale affiliate-database.

Gebruik: python3 build_cards.py
"""
import html
import json
import re
from pathlib import Path

START = "<!-- TOOLS:START (auto-generated by build_cards.py — niet handmatig bewerken) -->"
END = "<!-- TOOLS:END -->"

CARD = """\
                <div class="tool-card group bg-slate-900/40 p-6 rounded-xl border border-slate-800 hover:border-indigo-500 hover:bg-slate-900/70 transition-all duration-300 flex flex-col h-full shadow-lg shadow-black/20" data-category="{category_attr}">
                    <div class="flex items-start justify-between mb-5">
                        <div class="w-12 h-12 rounded-lg bg-white p-1.5 border border-slate-700 shadow-sm flex items-center justify-center overflow-hidden">
                            <img src="https://www.google.com/s2/favicons?domain={domain}&amp;sz=128" alt="{name} logo" class="w-full h-full object-contain" loading="lazy" width="48" height="48">
                        </div>
                        <span class="text-[10px] uppercase font-mono tracking-widest text-indigo-400 bg-indigo-950/40 px-2.5 py-1 rounded border border-indigo-900/30 text-right max-w-[60%]">{category}</span>
                    </div>
                    <h3 class="font-bold text-xl text-white group-hover:text-indigo-400 transition-colors mb-3">{name}</h3>
                    <p class="text-sm text-slate-400 leading-relaxed mb-6 flex-grow">{desc}</p>
                    <a href="{link}" target="_blank" rel="sponsored noopener noreferrer" class="text-sm font-medium text-slate-300 hover:text-white flex items-center justify-between w-full mt-auto border-t border-slate-800/60 pt-4 group/link">
                        <span>View Software</span>
                        <span class="text-indigo-500 group-hover/link:translate-x-1 transition-transform">&rarr;</span>
                    </a>
                </div>"""


def main():
    root = Path(__file__).parent
    tools = json.loads((root / "data.json").read_text(encoding="utf-8"))
    tools.sort(key=lambda t: t["name"].lower())

    cards = "\n".join(
        CARD.format(
            category_attr=html.escape(t["category"], quote=True),
            category=html.escape(t["category"]),
            domain=html.escape(t.get("domain", "example.com"), quote=True),
            name=html.escape(t["name"]),
            desc=html.escape(t["desc"]),
            link=html.escape(t["link"], quote=True),
        )
        for t in tools
    )

    index = (root / "index.html").read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + ".*?" + re.escape(END), re.S)
    block = f"{START}\n{cards}\n                {END}"
    if not pattern.search(index):
        raise SystemExit("Markers TOOLS:START/TOOLS:END niet gevonden in index.html")
    new_index = pattern.sub(lambda m: block, index)

    # JSON-LD ItemList synchroon houden
    items = [
        {
            "@type": "ListItem",
            "position": i + 1,
            "name": t["name"],
            "url": f"https://{t['domain']}" if t.get("domain") else None,
        }
        for i, t in enumerate(tools)
    ]
    for it in items:
        if it["url"] is None:
            del it["url"]
    itemlist = json.dumps(
        {
            "@context": "https://schema.org",
            "@type": "ItemList",
            "name": "Office Software Marketplace directory",
            "numberOfItems": len(tools),
            "itemListElement": items,
        },
        ensure_ascii=False,
    )
    new_index = re.sub(
        r'(<script type="application/ld\+json" id="itemlist-schema">).*?(</script>)',
        lambda m: m.group(1) + itemlist + m.group(2),
        new_index,
        flags=re.S,
    )

    if new_index != index:
        (root / "index.html").write_text(new_index, encoding="utf-8")
        print(f"index.html bijgewerkt: {len(tools)} kaarten")
    else:
        print(f"geen wijzigingen ({len(tools)} kaarten)")


if __name__ == "__main__":
    main()
