#!/usr/bin/env python3
"""Bouwt de statische toolkaarten in index.html uit data.json, zodat de
directory indexeerbaar is zonder JavaScript. Draait in de GitHub Action
(sync-data.yml) na elke update van de centrale affiliate-database.

Telt daarnaast per tool de in-depth reviews op aibuildermarketplace.com
(data-tool-attributen op /b2b/) en toont die op de kaart met een link naar
de artikelen. Lukt het ophalen niet, dan valt het terug op reviews.json.

Gebruik: python3 build_cards.py
"""
import html
import json
import re
import urllib.request
from pathlib import Path
from urllib.parse import quote

START = "<!-- TOOLS:START (auto-generated by build_cards.py — niet handmatig bewerken) -->"
END = "<!-- TOOLS:END -->"
AIBM_B2B = "https://aibuildermarketplace.com/b2b/"

CARD = """\
                <div class="tool-card group bg-slate-900/40 p-6 rounded-xl border border-slate-800 hover:border-indigo-500 hover:bg-slate-900/70 transition-all duration-300 flex flex-col h-full shadow-lg shadow-black/20" data-category="{category_attr}">
                    <div class="flex items-start justify-between mb-5">
                        <div class="w-12 h-12 rounded-lg bg-white p-1.5 border border-slate-700 shadow-sm flex items-center justify-center overflow-hidden">
                            <img src="https://logo.clearbit.com/{domain}" alt="{name} logo" class="w-full h-full object-contain" loading="lazy" width="48" height="48" onerror="this.onerror=null;this.src='https://www.google.com/s2/favicons?domain={domain}&amp;sz=128'">
                        </div>
                        <span class="text-[10px] uppercase font-mono tracking-widest text-indigo-400 bg-indigo-950/40 px-2.5 py-1 rounded border border-indigo-900/30 text-right max-w-[60%]">{category}</span>
                    </div>
                    <h3 class="font-bold text-xl text-white group-hover:text-indigo-400 transition-colors mb-3">{name}</h3>{alt_row}{reviews_row}
                    <p class="text-sm text-slate-400 leading-relaxed mb-6 flex-grow">{desc}</p>
                    <div class="mt-auto flex items-center gap-2">
                    <a href="{link}" target="_blank" rel="sponsored noopener noreferrer" class="tool-cta flex-1 inline-flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm px-4 py-2.5 rounded-lg transition-colors">
                        <span>Visit {name}</span><span aria-hidden="true">&rarr;</span>
                    </a>
                    <button class="shortlist-btn" data-name="{name}" aria-label="Save to shortlist">&#9734;</button>
                    </div>
                </div>"""

REVIEWS_ROW = """
                    <a href="{reviews_url}" target="_blank" rel="noopener" class="inline-flex items-center gap-1.5 text-xs text-indigo-300 hover:text-white mb-3 transition-colors"><span class="text-emerald-400">&#9679;</span> {n} in-depth review{s} &rarr;</a>"""


# Tools met een handgebouwde single-page hero op AIBM (niet in de auto-gegenereerde
# /b2b/-index, dus tel-mechanisme vindt ze niet). Directe koppeling + telling.
DIRECT_REVIEWS = {
    "Aspire": ("https://aibuildermarketplace.com/b2b/aspire-review/", 1),
    "1Password": ("https://aibuildermarketplace.com/b2b/1password-review/", 1),
    "Payoneer": ("https://aibuildermarketplace.com/b2b/payoneer-review/", 1),
    "NordVPN": ("https://aibuildermarketplace.com/b2b/nordvpn-review/", 1),
    "Apollo": ("https://aibuildermarketplace.com/b2b/apollo-review/", 1),
    "Streak": ("https://aibuildermarketplace.com/b2b/streak-review/", 1),
    "AWeber": ("https://aibuildermarketplace.com/b2b/aweber-review/", 1),
}


ALT_ROW = """\n                    <div class="text-[11px] text-slate-500 mb-3">&#8596; Alternative to <span class="text-slate-300 font-medium">{leader}</span></div>"""


def alt_row_for(t):
    r = t.get("replaces")
    return ALT_ROW.format(leader=html.escape(r)) if r else ""


def norm(name):
    return re.sub(r"[^a-z0-9]", "", name.lower())


def fetch_review_counts(root):
    """Tel data-tool-voorkomens op de live AIBM-reviewsindex; cache in reviews.json."""
    cache = root / "reviews.json"
    try:
        with urllib.request.urlopen(AIBM_B2B, timeout=20) as r:
            page = r.read().decode("utf-8", errors="replace")
        counts = {}
        for tool in re.findall(r'data-tool="([^"]+)"', page):
            counts[tool] = counts.get(tool, 0) + 1
        if counts:
            cache.write_text(json.dumps(counts, indent=1, ensure_ascii=False, sort_keys=True), encoding="utf-8")
            return counts
    except Exception as e:
        print(f"waarschuwing: AIBM-fetch mislukt ({e}); gebruik cache")
    if cache.exists():
        return json.loads(cache.read_text(encoding="utf-8"))
    return {}


def main():
    root = Path(__file__).parent
    tools = json.loads((root / "data.json").read_text(encoding="utf-8"))
    tools.sort(key=lambda t: t["name"].lower())

    raw_counts = fetch_review_counts(root)
    counts = {norm(k): (k, v) for k, v in raw_counts.items()}

    aibm_b2b = root.parent / "aibuildermarketplace-main" / "b2b"
    review_folders = ({p.name for p in aibm_b2b.iterdir() if p.is_dir()}
                      if aibm_b2b.is_dir() else set())

    def _rslug(name):
        return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") + "-review"

    # ecosysteem-UTM zodat cross-site clicks naar AIBM als 'ecosystem' attribueren
    # i.p.v. (direct)/(none) in GA4
    def _eco(u):
        return u + ("&" if "?" in u else "?") + "utm_source=officesoftwaremarketplace&utm_medium=ecosystem"

    def reviews_row(t):
        # directe deeplink als de review als map bestaat (sterker voor SEO; werkt ook
        # vóór Victors live-index-scan), anders DIRECT_REVIEWS of de ?tool=-filter
        rs = _rslug(t["name"])
        hit = counts.get(norm(t["name"]))
        if rs in review_folders:
            n = hit[1] if hit else DIRECT_REVIEWS.get(t["name"], (None, 1))[1]
            return REVIEWS_ROW.format(reviews_url=_eco(f"https://aibuildermarketplace.com/b2b/{rs}/"),
                                      n=n, s="" if n == 1 else "s")
        direct = DIRECT_REVIEWS.get(t["name"])
        if direct:
            url, n = direct
            return REVIEWS_ROW.format(reviews_url=_eco(url), n=n, s="" if n == 1 else "s")
        if not hit:
            return ""
        aibm_name, n = hit
        url = f"{AIBM_B2B}?tool={quote(aibm_name)}"
        return REVIEWS_ROW.format(reviews_url=_eco(url), n=n, s="" if n == 1 else "s")

    matched = sum(1 for t in tools if norm(t["name"]) in counts)
    print(f"review-koppeling: {matched} van {len(tools)} tools hebben AIBM-reviews")

    cards = "\n".join(
        CARD.format(
            category_attr=html.escape(t["category"], quote=True),
            category=html.escape(t["category"]),
            domain=html.escape(t.get("domain", "example.com"), quote=True),
            name=html.escape(t["name"]),
            desc=html.escape(t["desc"]),
            link=html.escape(t["link"], quote=True),
            reviews_row=reviews_row(t),
            alt_row=alt_row_for(t),
        )
        for t in tools
    )

    index = (root / "index.html").read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + ".*?" + re.escape(END), re.S)
    block = f"{START}\n{cards}\n                {END}"
    if not pattern.search(index):
        raise SystemExit("Markers TOOLS:START/TOOLS:END niet gevonden in index.html")
    new_index = pattern.sub(lambda m: block, index)

    # JSON-LD ItemList synchroon houden
    items = [
        {
            "@type": "ListItem",
            "position": i + 1,
            "name": t["name"],
            "url": f"https://{t['domain']}" if t.get("domain") else None,
        }
        for i, t in enumerate(tools)
    ]
    for it in items:
        if it["url"] is None:
            del it["url"]
    itemlist = json.dumps(
        {
            "@context": "https://schema.org",
            "@type": "ItemList",
            "name": "Office Software Marketplace directory",
            "numberOfItems": len(tools),
            "itemListElement": items,
        },
        ensure_ascii=False,
    )
    new_index = re.sub(
        r'(<script type="application/ld\+json" id="itemlist-schema">).*?(</script>)',
        lambda m: m.group(1) + itemlist + m.group(2),
        new_index,
        flags=re.S,
    )

    if new_index != index:
        (root / "index.html").write_text(new_index, encoding="utf-8")
        print(f"index.html bijgewerkt: {len(tools)} kaarten")
    else:
        print(f"geen wijzigingen ({len(tools)} kaarten)")


if __name__ == "__main__":
    main()
